// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.FlexDi.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionFormats {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionFormats() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExceptionFormats", typeof(ExceptionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ResolutionInfoCacheMustNotBeNull {
            get {
                return ResourceManager.GetString("ResolutionInfoCacheMustNotBeNull", resourceCulture);
            }
        }
        
        internal static string CircularDependencyDetected {
            get {
                return ResourceManager.GetString("CircularDependencyDetected", resourceCulture);
            }
        }
        
        internal static string ImplementationTypeMustHaveAConstructor {
            get {
                return ResourceManager.GetString("ImplementationTypeMustHaveAConstructor", resourceCulture);
            }
        }
        
        internal static string AmbiguousConstructor {
            get {
                return ResourceManager.GetString("AmbiguousConstructor", resourceCulture);
            }
        }
        
        internal static string CannotResolveComponentType {
            get {
                return ResourceManager.GetString("CannotResolveComponentType", resourceCulture);
            }
        }
        
        internal static string TypeToResolveMustBeNullableReferenceType {
            get {
                return ResourceManager.GetString("TypeToResolveMustBeNullableReferenceType", resourceCulture);
            }
        }
        
        internal static string CannotReRegisterAfterResolution {
            get {
                return ResourceManager.GetString("CannotReRegisterAfterResolution", resourceCulture);
            }
        }
        
        internal static string ContainerIsDisposed {
            get {
                return ResourceManager.GetString("ContainerIsDisposed", resourceCulture);
            }
        }
        
        internal static string ResolverFactoryMustNotReturnNull {
            get {
                return ResourceManager.GetString("ResolverFactoryMustNotReturnNull", resourceCulture);
            }
        }
        
        internal static string FailedToResolveParameter {
            get {
                return ResourceManager.GetString("FailedToResolveParameter", resourceCulture);
            }
        }
        
        internal static string InstanceRegistrationsAreAlwaysCacheable {
            get {
                return ResourceManager.GetString("InstanceRegistrationsAreAlwaysCacheable", resourceCulture);
            }
        }
        
        internal static string LateBoundResolverMayOnlyBeSetOnce {
            get {
                return ResourceManager.GetString("LateBoundResolverMayOnlyBeSetOnce", resourceCulture);
            }
        }
        
        internal static string LazyResolutionException {
            get {
                return ResourceManager.GetString("LazyResolutionException", resourceCulture);
            }
        }
        
        internal static string LazyResolutionFailure {
            get {
                return ResourceManager.GetString("LazyResolutionFailure", resourceCulture);
            }
        }
        
        internal static string MissingEnumerationContant {
            get {
                return ResourceManager.GetString("MissingEnumerationContant", resourceCulture);
            }
        }
        
        internal static string InvalidOpenGenericRegistration {
            get {
                return ResourceManager.GetString("InvalidOpenGenericRegistration", resourceCulture);
            }
        }
        
        internal static string RequestMustBeForGenericType {
            get {
                return ResourceManager.GetString("RequestMustBeForGenericType", resourceCulture);
            }
        }
    }
}
